// Author: Harsha Gundala
// template.ts — edge-function scaffold wrapped around operator-authored tool logic.

/**
 * The operator writes only the body of `run(input, env)`. The wrapper owns
 * parsing, auth, and the response envelope so every minted tool behaves identically.
 */
export function wrapToolSource(slug: string, runSource: string): string {
  return `// Auto-generated by Harsha's Amazing Call Center — tool: ${slug}
export const config = { runtime: "edge" };

${runSource}

export default async function handler(req) {
  if (req.method !== "POST") return new Response("POST only", { status: 405 });
  const auth = req.headers.get("authorization") ?? "";
  if (auth !== \`Bearer \${process.env.TOOL_SHARED_SECRET}\`) {
    return new Response("unauthorized", { status: 401 });
  }
  try {
    const input = await req.json();
    const output = await run(input, process.env);
    return Response.json({ ok: true, output });
  } catch (e) {
    return Response.json({ ok: false, error: String(e && e.message || e) }, { status: 500 });
  }
}
`;
}

export const RUN_SIGNATURE_DOC = `Write a self-contained JavaScript async function:
  async function run(input, env) { ... return <json-serializable>; }
- input: object matching the tool's JSON Schema.
- env: process.env — reference secrets by name (declare them in env_var_names; values come from the org vault).
- Use fetch() for any external API. No imports, no filesystem. Must complete in <20s.`;
