-- Crash-safe dispatch ownership, stable integration identities, and immutable read-back proofs.
-- Provider request IDs are replay correlation only. invocation_id is generated by the gateway
-- and is the only identity integrations may use for idempotency or reconciliation.

-- Record whether this database predates the durable dispatch boundary. This must be captured
-- before adding columns so a deliberate manual reapply cannot reinterpret live reservations.
CREATE TEMP TABLE IF NOT EXISTS hacc_012_upgrade_state (
  legacy_dispatch_boundary boolean NOT NULL
);
TRUNCATE hacc_012_upgrade_state;
INSERT INTO hacc_012_upgrade_state
SELECT NOT EXISTS (
  SELECT 1 FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'flow_action_receipts'
    AND column_name = 'dispatch_started_at'
);

-- A prerelease reapply may already have the lifecycle trigger. Suspend it inside the migration
-- transaction while exact legacy state is normalized, then recreate it below.
DROP TRIGGER IF EXISTS trg_flow_action_receipt_lifecycle
  ON flow_action_receipts;

-- Early prerelease revisions used uuid here, but the integration assertion protocol forwards an
-- exact 24-character base64url identity. Upgrade either shape in place before adding constraints.
DO $$
DECLARE
  current_type text;
BEGIN
  SELECT data_type INTO current_type
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND table_name = 'flow_action_receipts'
    AND column_name = 'invocation_id';

  IF current_type IS NULL THEN
    ALTER TABLE flow_action_receipts ADD COLUMN invocation_id text;
  ELSIF current_type = 'uuid' THEN
    ALTER TABLE flow_action_receipts
      ALTER COLUMN invocation_id TYPE text
      USING (
        regexp_replace(
          translate(encode(uuid_send(invocation_id), 'base64'), '+/', '-_'),
          '=+$',
          ''
        ) || '00'
      );
  ELSIF current_type <> 'text' THEN
    RAISE EXCEPTION 'unsupported flow_action_receipts.invocation_id type: %', current_type;
  END IF;
END $$;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS provider_invocation_id text;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS dispatch_lease_expires_at timestamptz;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS owner_heartbeat_at timestamptz;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS dispatch_started_at timestamptz;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS dispatch_attempt int NOT NULL DEFAULT 0;
ALTER TABLE flow_action_receipts ADD COLUMN IF NOT EXISTS reconciliation_proof_id uuid;

UPDATE flow_action_receipts
SET invocation_id = regexp_replace(
                      translate(encode(uuid_send(id), 'base64'), '+/', '-_'),
                      '=+$',
                      ''
                    ) || '00'
WHERE invocation_id IS NULL
   OR invocation_id !~ '^[A-Za-z0-9_-]{24}$';

-- Pre-migration reservations have no trustworthy process-boundary evidence. Conservatively mark
-- them dispatched/indeterminate instead of making a possibly committed effect redispatchable.
UPDATE flow_action_receipts
SET status = 'indeterminate',
    delivery_state = 'unknown',
    dispatch_started_at = COALESCE(dispatch_started_at, reserved_at),
    dispatch_attempt = GREATEST(dispatch_attempt, 1),
    dispatch_lease_expires_at = COALESCE(dispatch_lease_expires_at, reserved_at),
    owner_heartbeat_at = COALESCE(owner_heartbeat_at, reserved_at),
    error = COALESCE(error, '{"message":"legacy reservation migrated as indeterminate"}'::jsonb),
    settled_at = COALESCE(settled_at, now())
WHERE status = 'reserved'
  AND (SELECT legacy_dispatch_boundary FROM hacc_012_upgrade_state);

UPDATE flow_action_receipts
SET dispatch_started_at = COALESCE(dispatch_started_at, reserved_at),
    dispatch_attempt = GREATEST(dispatch_attempt, 1),
    dispatch_lease_expires_at = COALESCE(dispatch_lease_expires_at, reserved_at),
    owner_heartbeat_at = COALESCE(owner_heartbeat_at, reserved_at)
WHERE status IN ('succeeded', 'indeterminate')
  AND (dispatch_started_at IS NULL OR dispatch_attempt < 1
       OR dispatch_lease_expires_at IS NULL OR owner_heartbeat_at IS NULL);

UPDATE flow_action_receipts
SET dispatch_lease_expires_at = COALESCE(dispatch_lease_expires_at, reserved_at),
    owner_heartbeat_at = COALESCE(owner_heartbeat_at, reserved_at)
WHERE dispatch_lease_expires_at IS NULL OR owner_heartbeat_at IS NULL;

-- Runtime timestamps use the strict RFC3339 UTC form accepted by z.iso.datetime(). Legacy JSON
-- may contain an otherwise-valid offset or an impossible calendar date. Prefer the typed ledger
-- timestamp; only parse a JSON fallback inside an exception boundary, then emit canonical UTC.
CREATE OR REPLACE FUNCTION pg_temp.hacc_012_canonical_timestamp(
  candidate text,
  authoritative timestamptz,
  fallback timestamptz
) RETURNS text LANGUAGE plpgsql AS $$
DECLARE
  selected timestamptz;
BEGIN
  IF authoritative IS NOT NULL AND isfinite(authoritative) THEN
    selected := authoritative;
  ELSIF candidate ~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]+)?(Z|[+-][0-9]{2}:[0-9]{2})$' THEN
    BEGIN
      selected := candidate::timestamptz;
      IF NOT isfinite(selected) THEN selected := NULL; END IF;
    EXCEPTION WHEN OTHERS THEN
      selected := NULL;
    END;
  END IF;
  IF selected IS NULL THEN
    selected := CASE WHEN fallback IS NOT NULL AND isfinite(fallback)
      THEN fallback ELSE clock_timestamp() END;
  END IF;
  RETURN to_char(selected AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
END $$;

-- Keep the embedded replay state consistent with the ledger migration in one revision.
WITH migration_context AS MATERIALIZED (
  SELECT legacy_dispatch_boundary,
         clock_timestamp() AS migration_ts
  FROM hacc_012_upgrade_state
), rewritten AS (
  SELECT fr.call_id,
         COALESCE(jsonb_agg(
           CASE
             WHEN receipt IS NULL THEN NULL
             WHEN migration_context.legacy_dispatch_boundary
                  AND receipt->>'status' = 'reserved' THEN
               receipt || jsonb_build_object(
                 'invocationId', COALESCE(
                   far.invocation_id,
                   regexp_replace(
                     translate(encode(uuid_send((receipt->>'id')::uuid), 'base64'), '+/', '-_'),
                     '=+$',
                     ''
                   ) || '00'
                 ),
                 'status', 'indeterminate',
                 'reservedAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'reservedAt', far.reserved_at, migration_context.migration_ts
                 ),
                 'dispatchStartedAt', pg_temp.hacc_012_canonical_timestamp(
                   COALESCE(receipt->>'dispatchStartedAt', receipt->>'reservedAt'),
                   far.dispatch_started_at,
                   COALESCE(far.reserved_at, migration_context.migration_ts)
                 ),
                 'dispatchAttempt', GREATEST(COALESCE((receipt->>'dispatchAttempt')::int, 0), 1),
                 'error', 'legacy reservation migrated as indeterminate',
                 'settledAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'settledAt', far.settled_at, migration_context.migration_ts
                 )
               )
             WHEN receipt->>'status' IN ('succeeded', 'indeterminate') THEN
               receipt || jsonb_build_object(
                 'invocationId', COALESCE(
                   far.invocation_id,
                   regexp_replace(
                     translate(encode(uuid_send((receipt->>'id')::uuid), 'base64'), '+/', '-_'),
                     '=+$',
                     ''
                   ) || '00'
                 ),
                 'reservedAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'reservedAt', far.reserved_at, migration_context.migration_ts
                 ),
                 'dispatchStartedAt', pg_temp.hacc_012_canonical_timestamp(
                   COALESCE(receipt->>'dispatchStartedAt', receipt->>'reservedAt'),
                   far.dispatch_started_at,
                   COALESCE(far.reserved_at, migration_context.migration_ts)
                 ),
                 'dispatchAttempt', GREATEST(COALESCE((receipt->>'dispatchAttempt')::int, 0), 1),
                 'settledAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'settledAt', far.settled_at, migration_context.migration_ts
                 )
               )
             WHEN receipt->>'status' = 'failed' THEN
               receipt || jsonb_build_object(
                 'invocationId', COALESCE(
                   far.invocation_id,
                   regexp_replace(
                     translate(encode(uuid_send((receipt->>'id')::uuid), 'base64'), '+/', '-_'),
                     '=+$',
                     ''
                   ) || '00'
                 ),
                 'reservedAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'reservedAt', far.reserved_at, migration_context.migration_ts
                 ),
                 'settledAt', pg_temp.hacc_012_canonical_timestamp(
                   receipt->>'settledAt', far.settled_at, migration_context.migration_ts
                 )
               ) || CASE
                 WHEN far.dispatch_started_at IS NOT NULL OR receipt ? 'dispatchStartedAt' THEN
                   jsonb_build_object(
                     'dispatchStartedAt', pg_temp.hacc_012_canonical_timestamp(
                       receipt->>'dispatchStartedAt', far.dispatch_started_at,
                       COALESCE(far.reserved_at, migration_context.migration_ts)
                     )
                   )
                 ELSE '{}'::jsonb
               END
             ELSE receipt || jsonb_build_object(
               'invocationId', COALESCE(
                 far.invocation_id,
                 regexp_replace(
                   translate(encode(uuid_send((receipt->>'id')::uuid), 'base64'), '+/', '-_'),
                   '=+$',
                   ''
                 ) || '00'
               ),
               'reservedAt', pg_temp.hacc_012_canonical_timestamp(
                 receipt->>'reservedAt', far.reserved_at, migration_context.migration_ts
               )
             )
           END
           ORDER BY ordinality
         ) FILTER (WHERE receipt IS NOT NULL), '[]'::jsonb) AS receipts,
         pg_temp.hacc_012_canonical_timestamp(
           fr.state->>'updatedAt', NULL, COALESCE(fr.updated_at, migration_context.migration_ts)
         ) AS state_updated_at
  FROM flow_runs fr
  CROSS JOIN migration_context
  LEFT JOIN LATERAL jsonb_array_elements(COALESCE(fr.state->'actionReceipts', '[]'::jsonb))
    WITH ORDINALITY AS items(receipt, ordinality) ON true
  LEFT JOIN flow_action_receipts far
    ON far.call_id = fr.call_id
   AND far.id = (receipt->>'id')::uuid
  GROUP BY fr.call_id, fr.state, fr.updated_at,
           migration_context.legacy_dispatch_boundary, migration_context.migration_ts
)
UPDATE flow_runs fr
SET state = jsonb_set(
              jsonb_set(
                jsonb_set(fr.state, '{actionReceipts}', rewritten.receipts, true),
                '{revision}', to_jsonb(fr.revision + 1), true
              ),
              '{updatedAt}', to_jsonb(rewritten.state_updated_at), true
            ),
    revision = fr.revision + 1,
    updated_at = now()
FROM rewritten
WHERE rewritten.call_id = fr.call_id
  AND (
    rewritten.receipts IS DISTINCT FROM COALESCE(fr.state->'actionReceipts', '[]'::jsonb)
    OR fr.state->>'updatedAt' IS DISTINCT FROM rewritten.state_updated_at
  );

ALTER TABLE flow_action_receipts ALTER COLUMN invocation_id SET NOT NULL;
ALTER TABLE flow_action_receipts ALTER COLUMN dispatch_lease_expires_at SET NOT NULL;
ALTER TABLE flow_action_receipts ALTER COLUMN owner_heartbeat_at SET NOT NULL;

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_invocation_id_valid;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_invocation_id_valid
  CHECK (invocation_id ~ '^[A-Za-z0-9_-]{24}$');

-- `IF NOT EXISTS` silently accepts a weaker prerelease index with the same name. Authority
-- indexes must either be exact or make the upgrade fail closed with a repairable diagnostic.
CREATE OR REPLACE FUNCTION pg_temp.hacc_012_require_index(
  index_name text,
  ddl text,
  expected_definition text
) RETURNS void LANGUAGE plpgsql AS $$
DECLARE
  index_oid regclass;
  actual_definition text;
BEGIN
  index_oid := to_regclass(format('public.%I', index_name));
  IF index_oid IS NULL THEN
    EXECUTE ddl;
    index_oid := to_regclass(format('public.%I', index_name));
  END IF;
  SELECT pg_get_indexdef(index_oid) INTO actual_definition;
  IF actual_definition IS DISTINCT FROM expected_definition THEN
    RAISE EXCEPTION 'authority index % has unexpected definition: %', index_name, actual_definition;
  END IF;
END $$;

SELECT pg_temp.hacc_012_require_index(
  'uq_flow_action_provider_invocation',
  'CREATE UNIQUE INDEX uq_flow_action_provider_invocation ON public.flow_action_receipts(call_id, provider_invocation_id) WHERE provider_invocation_id IS NOT NULL',
  'CREATE UNIQUE INDEX uq_flow_action_provider_invocation ON public.flow_action_receipts USING btree (call_id, provider_invocation_id) WHERE (provider_invocation_id IS NOT NULL)'
);
SELECT pg_temp.hacc_012_require_index(
  'uq_flow_action_downstream_invocation',
  'CREATE UNIQUE INDEX uq_flow_action_downstream_invocation ON public.flow_action_receipts(call_id, invocation_id)',
  'CREATE UNIQUE INDEX uq_flow_action_downstream_invocation ON public.flow_action_receipts USING btree (call_id, invocation_id)'
);
SELECT pg_temp.hacc_012_require_index(
  'uq_flow_action_receipt_call',
  'CREATE UNIQUE INDEX uq_flow_action_receipt_call ON public.flow_action_receipts(id, call_id)',
  'CREATE UNIQUE INDEX uq_flow_action_receipt_call ON public.flow_action_receipts USING btree (id, call_id)'
);
SELECT pg_temp.hacc_012_require_index(
  'idx_flow_action_expired_owners',
  'CREATE INDEX idx_flow_action_expired_owners ON public.flow_action_receipts(call_id, dispatch_lease_expires_at) WHERE status = ''reserved''',
  'CREATE INDEX idx_flow_action_expired_owners ON public.flow_action_receipts USING btree (call_id, dispatch_lease_expires_at) WHERE (status = ''reserved''::text)'
);

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_receipts_delivery_state_check;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_receipts_delivery_state_check
  CHECK (delivery_state IN ('not_sent','accepted','rejected','committed','unknown'));

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_terminal_dispatch_valid;
ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_dispatch_attempt_valid;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_dispatch_attempt_valid
  CHECK (dispatch_attempt >= 0 AND (dispatch_started_at IS NULL OR dispatch_attempt >= 1));
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_terminal_dispatch_valid CHECK (
    (status IN ('succeeded','indeterminate') AND dispatch_started_at IS NOT NULL)
    OR (status = 'failed' AND (dispatch_started_at IS NULL OR delivery_state = 'rejected'))
    OR status = 'reserved'
  );
ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_settlement_time_valid;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_settlement_time_valid CHECK (
    (status = 'reserved' AND settled_at IS NULL)
    OR (status <> 'reserved' AND settled_at IS NOT NULL)
  );

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_receipt_authority_shape;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_receipt_authority_shape CHECK (
    runtime_digest ~ '^[a-f0-9]{64}$'
    AND arguments_hash ~ '^[a-f0-9]{64}$'
    AND idempotency_key ~ '^[a-f0-9]{64}$'
    AND (provider_invocation_id IS NULL OR length(provider_invocation_id) BETWEEN 1 AND 256)
    AND (result_hash IS NULL OR result_hash ~ '^[a-f0-9]{64}$')
    AND ((result IS NULL) = (result_hash IS NULL))
  );

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_receipt_outcome_shape;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_receipt_outcome_shape CHECK (
    (status = 'reserved'
      AND result IS NULL AND result_hash IS NULL AND error IS NULL
      AND settled_at IS NULL AND reconciliation_proof_id IS NULL
      AND delivery_state IN ('not_sent', 'unknown'))
    OR (status = 'succeeded'
      AND error IS NULL AND settled_at IS NOT NULL AND delivery_state = 'committed')
    OR (status = 'failed'
      AND result IS NULL AND result_hash IS NULL AND error IS NOT NULL
      AND settled_at IS NOT NULL AND delivery_state IN ('not_sent', 'rejected'))
    OR (status = 'indeterminate'
      AND result IS NULL AND result_hash IS NULL AND error IS NOT NULL
      AND settled_at IS NOT NULL AND reconciliation_proof_id IS NULL
      AND delivery_state IN ('accepted', 'unknown'))
  );

CREATE TABLE IF NOT EXISTS flow_action_reconciliation_proofs (
  id uuid PRIMARY KEY,
  call_id uuid NOT NULL REFERENCES calls(id) ON DELETE CASCADE,
  action_receipt_id uuid NOT NULL,
  runtime_digest text NOT NULL CHECK (runtime_digest ~ '^[a-f0-9]{64}$'),
  policy_hash text NOT NULL CHECK (policy_hash ~ '^[a-f0-9]{64}$'),
  attempt int NOT NULL CHECK (attempt > 0),
  query_tool text NOT NULL,
  query_arguments jsonb NOT NULL,
  query_arguments_hash text NOT NULL CHECK (query_arguments_hash ~ '^[a-f0-9]{64}$'),
  predicate jsonb NOT NULL,
  predicate_hash text NOT NULL CHECK (predicate_hash ~ '^[a-f0-9]{64}$'),
  authoritative_result_path text NOT NULL,
  status text NOT NULL CHECK (status IN ('querying','committed','absent','mismatch','error')),
  owner_token uuid NOT NULL,
  lease_expires_at timestamptz NOT NULL,
  proof_result jsonb,
  proof_result_hash text,
  authoritative_result jsonb,
  authoritative_result_hash text,
  error jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz,
  UNIQUE (id, call_id),
  UNIQUE (action_receipt_id, attempt),
  FOREIGN KEY (action_receipt_id, call_id)
    REFERENCES flow_action_receipts(id, call_id) ON DELETE CASCADE,
  CONSTRAINT flow_action_reconciliation_terminal_shape CHECK (
    (status = 'querying' AND completed_at IS NULL AND proof_result IS NULL
      AND authoritative_result IS NULL AND error IS NULL)
    OR (status = 'committed' AND completed_at IS NOT NULL
      AND proof_result IS NOT NULL AND proof_result_hash IS NOT NULL
      AND authoritative_result IS NOT NULL AND authoritative_result_hash IS NOT NULL
      AND error IS NULL)
    OR (status IN ('absent','mismatch') AND completed_at IS NOT NULL
      AND proof_result IS NOT NULL AND proof_result_hash IS NOT NULL
      AND authoritative_result IS NULL AND authoritative_result_hash IS NULL AND error IS NULL)
    OR (status = 'error' AND completed_at IS NOT NULL
      AND proof_result IS NULL AND proof_result_hash IS NULL
      AND authoritative_result IS NULL AND authoritative_result_hash IS NULL
      AND error IS NOT NULL)
  )
);

-- Tighten prerelease installations where CREATE TABLE IF NOT EXISTS retained an earlier shape.
ALTER TABLE flow_action_reconciliation_proofs
  DROP CONSTRAINT IF EXISTS flow_action_reconciliation_terminal_shape;
ALTER TABLE flow_action_reconciliation_proofs
  ADD CONSTRAINT flow_action_reconciliation_terminal_shape CHECK (
    (status = 'querying' AND completed_at IS NULL AND proof_result IS NULL
      AND proof_result_hash IS NULL AND authoritative_result IS NULL
      AND authoritative_result_hash IS NULL AND error IS NULL)
    OR (status = 'committed' AND completed_at IS NOT NULL
      AND proof_result IS NOT NULL AND proof_result_hash IS NOT NULL
      AND authoritative_result IS NOT NULL AND authoritative_result_hash IS NOT NULL
      AND error IS NULL)
    OR (status IN ('absent','mismatch') AND completed_at IS NOT NULL
      AND proof_result IS NOT NULL AND proof_result_hash IS NOT NULL
      AND authoritative_result IS NULL AND authoritative_result_hash IS NULL AND error IS NULL)
    OR (status = 'error' AND completed_at IS NOT NULL
      AND proof_result IS NULL AND proof_result_hash IS NULL
      AND authoritative_result IS NULL AND authoritative_result_hash IS NULL
      AND error IS NOT NULL)
  );

ALTER TABLE flow_action_reconciliation_proofs
  DROP CONSTRAINT IF EXISTS flow_action_reconciliation_result_hashes_valid;
ALTER TABLE flow_action_reconciliation_proofs
  ADD CONSTRAINT flow_action_reconciliation_result_hashes_valid CHECK (
    (proof_result_hash IS NULL OR proof_result_hash ~ '^[a-f0-9]{64}$')
    AND (authoritative_result_hash IS NULL OR authoritative_result_hash ~ '^[a-f0-9]{64}$')
  );

SELECT pg_temp.hacc_012_require_index(
  'uq_flow_action_active_reconciliation',
  'CREATE UNIQUE INDEX uq_flow_action_active_reconciliation ON public.flow_action_reconciliation_proofs(action_receipt_id) WHERE status = ''querying''',
  'CREATE UNIQUE INDEX uq_flow_action_active_reconciliation ON public.flow_action_reconciliation_proofs USING btree (action_receipt_id) WHERE (status = ''querying''::text)'
);
SELECT pg_temp.hacc_012_require_index(
  'idx_flow_action_reconciliation_call',
  'CREATE INDEX idx_flow_action_reconciliation_call ON public.flow_action_reconciliation_proofs(call_id, action_receipt_id, attempt)',
  'CREATE INDEX idx_flow_action_reconciliation_call ON public.flow_action_reconciliation_proofs USING btree (call_id, action_receipt_id, attempt)'
);

ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_reconciliation_proof_fk;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_reconciliation_proof_fk
  FOREIGN KEY (reconciliation_proof_id, call_id)
  REFERENCES flow_action_reconciliation_proofs(id, call_id);
ALTER TABLE flow_action_receipts
  DROP CONSTRAINT IF EXISTS flow_action_reconciliation_status_valid;
ALTER TABLE flow_action_receipts
  ADD CONSTRAINT flow_action_reconciliation_status_valid
  CHECK (reconciliation_proof_id IS NULL OR status IN ('succeeded','failed'));

CREATE OR REPLACE FUNCTION reject_terminal_flow_reconciliation_proof_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'querying' THEN
      RAISE EXCEPTION 'flow reconciliation proofs must begin in querying state';
    END IF;
    IF NEW.lease_expires_at <= clock_timestamp() THEN
      RAISE EXCEPTION 'flow reconciliation proof lease must be live at admission';
    END IF;
    PERFORM 1
    FROM flow_action_receipts
    WHERE id = NEW.action_receipt_id
      AND call_id = NEW.call_id
      AND status = 'indeterminate'
      AND runtime_digest = NEW.runtime_digest
      AND dispatch_started_at IS NOT NULL
      AND reconciliation_proof_id IS NULL;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'flow reconciliation proof is not bound to an eligible receipt';
    END IF;
    RETURN NEW;
  END IF;

  -- Explicit call erasure may cascade its evidence. A direct proof deletion while the parent call
  -- exists remains forbidden.
  IF TG_OP = 'DELETE' THEN
    PERFORM 1 FROM calls WHERE id = OLD.call_id;
    IF FOUND THEN
      RAISE EXCEPTION 'terminal flow reconciliation proofs are immutable';
    END IF;
    RETURN OLD;
  END IF;

  IF OLD.status <> 'querying' THEN
    RAISE EXCEPTION 'terminal flow reconciliation proofs are immutable';
  END IF;
  IF NEW.status = 'querying' THEN
    RAISE EXCEPTION 'active flow reconciliation proof authority is immutable';
  END IF;
  IF NEW.status IN ('committed', 'absent', 'mismatch')
     AND OLD.lease_expires_at <= clock_timestamp() THEN
    RAISE EXCEPTION 'expired flow reconciliation proof cannot become authoritative';
  END IF;
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.call_id IS DISTINCT FROM OLD.call_id
     OR NEW.action_receipt_id IS DISTINCT FROM OLD.action_receipt_id
     OR NEW.runtime_digest IS DISTINCT FROM OLD.runtime_digest
     OR NEW.policy_hash IS DISTINCT FROM OLD.policy_hash
     OR NEW.attempt IS DISTINCT FROM OLD.attempt
     OR NEW.query_tool IS DISTINCT FROM OLD.query_tool
     OR NEW.query_arguments IS DISTINCT FROM OLD.query_arguments
     OR NEW.query_arguments_hash IS DISTINCT FROM OLD.query_arguments_hash
     OR NEW.predicate IS DISTINCT FROM OLD.predicate
     OR NEW.predicate_hash IS DISTINCT FROM OLD.predicate_hash
     OR NEW.authoritative_result_path IS DISTINCT FROM OLD.authoritative_result_path
     OR NEW.owner_token IS DISTINCT FROM OLD.owner_token
     OR NEW.lease_expires_at IS DISTINCT FROM OLD.lease_expires_at
     OR NEW.created_at IS DISTINCT FROM OLD.created_at
     OR NEW.started_at IS DISTINCT FROM OLD.started_at THEN
    RAISE EXCEPTION 'flow reconciliation proof authority is immutable';
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_terminal_flow_reconciliation_proof_immutable
  ON flow_action_reconciliation_proofs;
CREATE TRIGGER trg_terminal_flow_reconciliation_proof_immutable
BEFORE INSERT OR UPDATE OR DELETE ON flow_action_reconciliation_proofs
FOR EACH ROW EXECUTE FUNCTION reject_terminal_flow_reconciliation_proof_mutation();

CREATE OR REPLACE FUNCTION enforce_flow_action_receipt_lifecycle()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  proof_authoritative_result jsonb;
  proof_authoritative_result_hash text;
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.status <> 'reserved'
       OR NEW.dispatch_started_at IS NOT NULL
       OR NEW.dispatch_attempt <> 0
       OR NEW.result IS NOT NULL
       OR NEW.result_hash IS NOT NULL
       OR NEW.error IS NOT NULL
       OR NEW.settled_at IS NOT NULL
       OR NEW.reconciliation_proof_id IS NOT NULL
       OR NEW.delivery_state <> 'not_sent' THEN
      RAISE EXCEPTION 'flow action receipts must begin as undispatched reservations';
    END IF;
    RETURN NEW;
  END IF;

  -- A call is the retention root. Permit only its explicit cascade, never direct receipt erasure.
  IF TG_OP = 'DELETE' THEN
    PERFORM 1 FROM calls WHERE id = OLD.call_id;
    IF FOUND THEN
      RAISE EXCEPTION 'flow action receipts cannot be deleted while their call exists';
    END IF;
    RETURN OLD;
  END IF;

  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.call_id IS DISTINCT FROM OLD.call_id
     OR NEW.runtime_digest IS DISTINCT FROM OLD.runtime_digest
     OR NEW.capability_epoch IS DISTINCT FROM OLD.capability_epoch
     OR NEW.step_path IS DISTINCT FROM OLD.step_path
     OR NEW.step_attempt IS DISTINCT FROM OLD.step_attempt
     OR NEW.tool IS DISTINCT FROM OLD.tool
     OR NEW.invocation_id IS DISTINCT FROM OLD.invocation_id
     OR NEW.provider_invocation_id IS DISTINCT FROM OLD.provider_invocation_id
     OR NEW.arguments IS DISTINCT FROM OLD.arguments
     OR NEW.arguments_hash IS DISTINCT FROM OLD.arguments_hash
     OR NEW.idempotency_key IS DISTINCT FROM OLD.idempotency_key
     OR NEW.reserved_at IS DISTINCT FROM OLD.reserved_at THEN
    RAISE EXCEPTION 'flow action receipt authority is immutable';
  END IF;

  IF OLD.status = 'reserved' AND NEW.status = 'reserved' THEN
    IF OLD.dispatch_started_at IS NULL AND NEW.dispatch_started_at IS NULL THEN
      IF NEW.dispatch_attempt IS DISTINCT FROM OLD.dispatch_attempt
         OR NEW.delivery_state IS DISTINCT FROM OLD.delivery_state
         OR (NEW.owner_token IS DISTINCT FROM OLD.owner_token
             AND OLD.dispatch_lease_expires_at > now()) THEN
        RAISE EXCEPTION 'invalid pre-dispatch receipt lease transition';
      END IF;
      RETURN NEW;
    END IF;
    IF OLD.dispatch_started_at IS NULL AND NEW.dispatch_started_at IS NOT NULL THEN
      IF NEW.owner_token IS DISTINCT FROM OLD.owner_token
         OR NEW.dispatch_attempt <> OLD.dispatch_attempt + 1
         OR NEW.delivery_state <> 'unknown' THEN
        RAISE EXCEPTION 'invalid flow action dispatch transition';
      END IF;
      RETURN NEW;
    END IF;
    IF OLD.dispatch_started_at IS NOT NULL
       AND NEW.dispatch_started_at IS NOT DISTINCT FROM OLD.dispatch_started_at
       AND NEW.dispatch_attempt = OLD.dispatch_attempt
       AND NEW.owner_token IS NOT DISTINCT FROM OLD.owner_token
       AND NEW.delivery_state IS NOT DISTINCT FROM OLD.delivery_state THEN
      RETURN NEW;
    END IF;
    RAISE EXCEPTION 'flow action dispatch boundary is immutable';
  END IF;

  IF OLD.status = 'reserved' AND NEW.status IN ('succeeded', 'failed', 'indeterminate') THEN
    IF NEW.owner_token IS DISTINCT FROM OLD.owner_token
       OR NEW.dispatch_started_at IS DISTINCT FROM OLD.dispatch_started_at
       OR NEW.dispatch_attempt IS DISTINCT FROM OLD.dispatch_attempt
       OR NEW.dispatch_lease_expires_at IS DISTINCT FROM OLD.dispatch_lease_expires_at
       OR NEW.owner_heartbeat_at IS DISTINCT FROM OLD.owner_heartbeat_at
       OR NEW.reconciliation_proof_id IS NOT NULL THEN
      RAISE EXCEPTION 'invalid flow action settlement transition';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.status = 'indeterminate' AND NEW.status = 'succeeded' THEN
    IF NEW.owner_token IS DISTINCT FROM OLD.owner_token
       OR NEW.dispatch_started_at IS DISTINCT FROM OLD.dispatch_started_at
       OR NEW.dispatch_attempt IS DISTINCT FROM OLD.dispatch_attempt
       OR NEW.dispatch_lease_expires_at IS DISTINCT FROM OLD.dispatch_lease_expires_at
       OR NEW.owner_heartbeat_at IS DISTINCT FROM OLD.owner_heartbeat_at
       OR NEW.reconciliation_proof_id IS NULL
       OR NEW.settled_at < OLD.settled_at THEN
      RAISE EXCEPTION 'invalid reconciled action transition';
    END IF;
    SELECT authoritative_result, authoritative_result_hash
      INTO proof_authoritative_result, proof_authoritative_result_hash
    FROM flow_action_reconciliation_proofs
    WHERE id = NEW.reconciliation_proof_id
      AND call_id = OLD.call_id
      AND action_receipt_id = OLD.id
      AND status = 'committed';
    IF NOT FOUND
       OR NEW.result IS DISTINCT FROM proof_authoritative_result
       OR NEW.result_hash IS DISTINCT FROM proof_authoritative_result_hash THEN
      RAISE EXCEPTION 'reconciled receipt is not backed by its exact committed proof';
    END IF;
    RETURN NEW;
  END IF;

  -- Forward-compatible with migration 026: an exact invocation-bound read-back may prove
  -- the original effect authoritatively absent. That proof terminalizes the old receipt as
  -- a rejected failure, so a new receipt identity can retry without ever redispatching the
  -- uncertain invocation. Reapplying 012 must preserve, not weaken, this later authority.
  IF OLD.status = 'indeterminate' AND NEW.status = 'failed' THEN
    IF NEW.owner_token IS DISTINCT FROM OLD.owner_token
       OR NEW.dispatch_started_at IS DISTINCT FROM OLD.dispatch_started_at
       OR NEW.dispatch_attempt IS DISTINCT FROM OLD.dispatch_attempt
       OR NEW.dispatch_lease_expires_at IS DISTINCT FROM OLD.dispatch_lease_expires_at
       OR NEW.owner_heartbeat_at IS DISTINCT FROM OLD.owner_heartbeat_at
       OR NEW.reconciliation_proof_id IS NULL
       OR NEW.settled_at < OLD.settled_at
       OR NEW.delivery_state <> 'rejected'
       OR NEW.result IS NOT NULL OR NEW.result_hash IS NOT NULL
       OR NEW.error IS DISTINCT FROM '{"code":"authoritative_absence_proven"}'::jsonb THEN
      RAISE EXCEPTION 'invalid authoritative-absence transition';
    END IF;
    PERFORM 1
    FROM flow_action_reconciliation_proofs
    WHERE id = NEW.reconciliation_proof_id
      AND call_id = OLD.call_id
      AND action_receipt_id = OLD.id
      AND runtime_digest = OLD.runtime_digest
      AND status = 'absent'
      AND proof_result IS NOT NULL
      AND proof_result_hash IS NOT NULL
      AND authoritative_result IS NULL
      AND authoritative_result_hash IS NULL;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'failed receipt is not backed by its exact authoritative-absence proof';
    END IF;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'terminal flow action receipt is immutable';
END $$;

DROP TRIGGER IF EXISTS trg_flow_action_receipt_lifecycle
  ON flow_action_receipts;
CREATE TRIGGER trg_flow_action_receipt_lifecycle
BEFORE INSERT OR UPDATE OR DELETE ON flow_action_receipts
FOR EACH ROW EXECUTE FUNCTION enforce_flow_action_receipt_lifecycle();

COMMENT ON COLUMN flow_action_receipts.provider_invocation_id IS
  'Call-scoped replay correlation supplied by a realtime provider; never forwarded as authority.';
COMMENT ON COLUMN flow_action_receipts.invocation_id IS
  'Gateway-generated stable integration identity, reused across replay, crash recovery, and proof.';
COMMENT ON COLUMN flow_action_receipts.dispatch_started_at IS
  'Irreversible durable boundary. Once set, automatic action redispatch is forbidden.';
COMMENT ON TABLE flow_action_reconciliation_proofs IS
  'Immutable read-only proof attempts used for exact committed promotion or authoritative-absence retry safety.';

DROP TABLE hacc_012_upgrade_state;
